export type Product = {
  id: string;
  name: string;
  price: number;
  comparePrice?: number | null;
  image: string;
  slug: string;
  rating: number;
  reviewCount: number;
  badge?: string | null;
  category: CategoryKey;
  inStock: boolean;
};

export type CategoryKey =
  | 'electronics'
  | 'clothing'
  | 'home-garden'
  | 'sports'
  | 'books';

export const CATEGORIES: Record<CategoryKey, { label: string; href: string }> =
  {
    'electronics': { label: 'Electronics', href: '/category/electronics' },
    'clothing': { label: 'Clothing', href: '/category/clothing' },
    'home-garden': { label: 'Home & Garden', href: '/category/home-garden' },
    'sports': { label: 'Sports', href: '/category/sports' },
    'books': { label: 'Books', href: '/category/books' },
  };

export const PRODUCTS: Product[] = [
  // Electronics (12+)
  {
    id: 'e-1',
    name: 'Wireless Bluetooth Headphones',
    price: 79.99,
    comparePrice: 99.99,
    image: 'https://source.unsplash.com/featured/800x600?headphones,audio',
    slug: 'wireless-bluetooth-headphones',
    rating: 4.5,
    reviewCount: 128,
    badge: 'Best Seller',
    category: 'electronics',
    inStock: true,
  },
  {
    id: 'e-2',
    name: 'Smart Fitness Watch',
    price: 199.99,
    comparePrice: 249.99,
    image: 'https://source.unsplash.com/featured/800x600?smartwatch,wearable',
    slug: 'smart-fitness-watch',
    rating: 4.8,
    reviewCount: 89,
    badge: 'New',
    category: 'electronics',
    inStock: true,
  },
  {
    id: 'e-3',
    name: 'Portable Bluetooth Speaker',
    price: 59.99,
    comparePrice: null,
    image: 'https://source.unsplash.com/featured/800x600?bluetooth,speaker',
    slug: 'portable-bluetooth-speaker',
    rating: 4.4,
    reviewCount: 167,
    badge: null,
    category: 'electronics',
    inStock: true,
  },
  {
    id: 'e-4',
    name: 'Wireless Charging Pad',
    price: 29.99,
    comparePrice: 39.99,
    image: 'https://source.unsplash.com/featured/800x600?wireless,charger',
    slug: 'wireless-charging-pad',
    rating: 4.6,
    reviewCount: 203,
    badge: 'Hot Deal',
    category: 'electronics',
    inStock: true,
  },
  {
    id: 'e-5',
    name: 'Noise Cancelling Earbuds',
    price: 99.99,
    comparePrice: 129.99,
    image: 'https://source.unsplash.com/featured/800x600?earbuds,wireless',
    slug: 'noise-cancelling-earbuds',
    rating: 4.2,
    reviewCount: 74,
    badge: null,
    category: 'electronics',
    inStock: true,
  },
  {
    id: 'e-6',
    name: 'Smart Home Hub',
    price: 89.99,
    comparePrice: 119.99,
    image: 'https://source.unsplash.com/featured/800x600?smart,home,hub',
    slug: 'smart-home-hub',
    rating: 4.7,
    reviewCount: 94,
    badge: 'Limited',
    category: 'electronics',
    inStock: true,
  },
  {
    id: 'e-7',
    name: '4K Action Camera',
    price: 149.99,
    comparePrice: 179.99,
    image: 'https://source.unsplash.com/featured/800x600?action,camera',
    slug: '4k-action-camera',
    rating: 4.1,
    reviewCount: 61,
    badge: null,
    category: 'electronics',
    inStock: true,
  },
  {
    id: 'e-8',
    name: 'USB-C Fast Charger 30W',
    price: 24.99,
    comparePrice: 29.99,
    image: 'https://source.unsplash.com/featured/800x600?usb-c,charger',
    slug: 'usb-c-fast-charger-30w',
    rating: 4.5,
    reviewCount: 210,
    badge: null,
    category: 'electronics',
    inStock: true,
  },
  {
    id: 'e-9',
    name: 'Portable Power Bank 20,000mAh',
    price: 39.99,
    comparePrice: 49.99,
    image:
      'https://source.unsplash.com/featured/800x600?powerbank,portable,charger',
    slug: 'portable-power-bank-20000',
    rating: 4.6,
    reviewCount: 330,
    badge: 'Hot Deal',
    category: 'electronics',
    inStock: true,
  },
  {
    id: 'e-10',
    name: 'Smart LED Light Bulb (4-Pack)',
    price: 34.99,
    comparePrice: 44.99,
    image: 'https://source.unsplash.com/featured/800x600?smart,bulb,light',
    slug: 'smart-led-light-bulb-4-pack',
    rating: 4.4,
    reviewCount: 145,
    badge: null,
    category: 'electronics',
    inStock: true,
  },
  {
    id: 'e-11',
    name: '1080p Webcam with Mic',
    price: 49.99,
    comparePrice: 59.99,
    image: 'https://source.unsplash.com/featured/800x600?webcam,computer',
    slug: '1080p-webcam-with-mic',
    rating: 4.3,
    reviewCount: 98,
    badge: null,
    category: 'electronics',
    inStock: true,
  },
  {
    id: 'e-12',
    name: 'Mechanical Gaming Keyboard',
    price: 89.99,
    comparePrice: 109.99,
    image: 'https://source.unsplash.com/featured/800x600?mechanical,keyboard',
    slug: 'mechanical-gaming-keyboard',
    rating: 4.7,
    reviewCount: 180,
    badge: 'Best Seller',
    category: 'electronics',
    inStock: true,
  },

  // Clothing (12+)
  {
    id: 'c-1',
    name: 'Classic Cotton T-Shirt',
    price: 19.99,
    comparePrice: 24.99,
    image: 'https://source.unsplash.com/featured/800x600?tshirt,fashion',
    slug: 'classic-cotton-tshirt',
    rating: 4.3,
    reviewCount: 220,
    badge: null,
    category: 'clothing',
    inStock: true,
  },
  {
    id: 'c-2',
    name: 'Slim Fit Jeans',
    price: 49.99,
    comparePrice: 59.99,
    image: 'https://source.unsplash.com/featured/800x600?jeans,denim',
    slug: 'slim-fit-jeans',
    rating: 4.5,
    reviewCount: 180,
    badge: 'Hot Deal',
    category: 'clothing',
    inStock: true,
  },
  {
    id: 'c-3',
    name: 'Hooded Sweatshirt',
    price: 39.99,
    comparePrice: 49.99,
    image: 'https://source.unsplash.com/featured/800x600?hoodie,sweatshirt',
    slug: 'hooded-sweatshirt',
    rating: 4.6,
    reviewCount: 156,
    badge: null,
    category: 'clothing',
    inStock: true,
  },
  {
    id: 'c-4',
    name: 'Athletic Sneakers',
    price: 69.99,
    comparePrice: 89.99,
    image: 'https://source.unsplash.com/featured/800x600?sneakers,shoes',
    slug: 'athletic-sneakers',
    rating: 4.4,
    reviewCount: 134,
    badge: 'New',
    category: 'clothing',
    inStock: true,
  },
  {
    id: 'c-5',
    name: 'Summer Dress',
    price: 59.99,
    comparePrice: 79.99,
    image: 'https://source.unsplash.com/featured/800x600?summer,dress',
    slug: 'summer-dress',
    rating: 4.2,
    reviewCount: 98,
    badge: null,
    category: 'clothing',
    inStock: true,
  },
  {
    id: 'c-6',
    name: 'Casual Button-Down Shirt',
    price: 29.99,
    comparePrice: 39.99,
    image: 'https://source.unsplash.com/featured/800x600?shirt,button-down',
    slug: 'casual-button-down-shirt',
    rating: 4.1,
    reviewCount: 76,
    badge: null,
    category: 'clothing',
    inStock: true,
  },
  {
    id: 'c-7',
    name: 'Puffer Jacket',
    price: 99.99,
    comparePrice: 129.99,
    image: 'https://source.unsplash.com/featured/800x600?puffer,jacket',
    slug: 'puffer-jacket',
    rating: 4.6,
    reviewCount: 88,
    badge: 'Limited',
    category: 'clothing',
    inStock: true,
  },
  {
    id: 'c-8',
    name: 'Yoga Pants',
    price: 34.99,
    comparePrice: 44.99,
    image: 'https://source.unsplash.com/featured/800x600?yoga,pants',
    slug: 'yoga-pants',
    rating: 4.7,
    reviewCount: 220,
    badge: 'Best Seller',
    category: 'clothing',
    inStock: true,
  },
  {
    id: 'c-9',
    name: 'Baseball Cap',
    price: 14.99,
    comparePrice: 19.99,
    image: 'https://source.unsplash.com/featured/800x600?baseball,cap',
    slug: 'baseball-cap',
    rating: 4.0,
    reviewCount: 54,
    badge: null,
    category: 'clothing',
    inStock: true,
  },
  {
    id: 'c-10',
    name: 'Leather Belt',
    price: 24.99,
    comparePrice: 29.99,
    image: 'https://source.unsplash.com/featured/800x600?leather,belt',
    slug: 'leather-belt',
    rating: 4.3,
    reviewCount: 60,
    badge: null,
    category: 'clothing',
    inStock: true,
  },
  {
    id: 'c-11',
    name: 'Running Shorts',
    price: 22.99,
    comparePrice: 27.99,
    image: 'https://source.unsplash.com/featured/800x600?running,shorts',
    slug: 'running-shorts',
    rating: 4.2,
    reviewCount: 70,
    badge: null,
    category: 'clothing',
    inStock: true,
  },
  {
    id: 'c-12',
    name: 'Wool Scarf',
    price: 19.99,
    comparePrice: 24.99,
    image: 'https://source.unsplash.com/featured/800x600?wool,scarf',
    slug: 'wool-scarf',
    rating: 4.5,
    reviewCount: 66,
    badge: null,
    category: 'clothing',
    inStock: true,
  },

  // Home & Garden (12+)
  {
    id: 'h-1',
    name: 'Premium Coffee Maker',
    price: 149.99,
    comparePrice: null,
    image: 'https://source.unsplash.com/featured/800x600?coffee,maker',
    slug: 'premium-coffee-maker',
    rating: 4.3,
    reviewCount: 56,
    badge: null,
    category: 'home-garden',
    inStock: true,
  },
  {
    id: 'h-2',
    name: 'Stainless Steel Cookware Set',
    price: 129.99,
    comparePrice: 159.99,
    image: 'https://source.unsplash.com/featured/800x600?cookware,set',
    slug: 'stainless-steel-cookware-set',
    rating: 4.5,
    reviewCount: 110,
    badge: 'Best Seller',
    category: 'home-garden',
    inStock: true,
  },
  {
    id: 'h-3',
    name: 'Memory Foam Pillow',
    price: 29.99,
    comparePrice: 39.99,
    image: 'https://source.unsplash.com/featured/800x600?memory,foam,pillow',
    slug: 'memory-foam-pillow',
    rating: 4.6,
    reviewCount: 140,
    badge: null,
    category: 'home-garden',
    inStock: true,
  },
  {
    id: 'h-4',
    name: 'Decorative Indoor Plant',
    price: 24.99,
    comparePrice: 29.99,
    image: 'https://source.unsplash.com/featured/800x600?indoor,plant',
    slug: 'decorative-indoor-plant',
    rating: 4.7,
    reviewCount: 80,
    badge: 'New',
    category: 'home-garden',
    inStock: true,
  },
  {
    id: 'h-5',
    name: 'LED Desk Lamp',
    price: 34.99,
    comparePrice: 44.99,
    image: 'https://source.unsplash.com/featured/800x600?desk,lamp',
    slug: 'led-desk-lamp',
    rating: 4.4,
    reviewCount: 95,
    badge: null,
    category: 'home-garden',
    inStock: true,
  },
  {
    id: 'h-6',
    name: 'Non-Stick Baking Set',
    price: 39.99,
    comparePrice: 49.99,
    image: 'https://source.unsplash.com/featured/800x600?baking,set',
    slug: 'non-stick-baking-set',
    rating: 4.3,
    reviewCount: 72,
    badge: null,
    category: 'home-garden',
    inStock: true,
  },
  {
    id: 'h-7',
    name: 'Bamboo Cutting Board',
    price: 19.99,
    comparePrice: 24.99,
    image: 'https://source.unsplash.com/featured/800x600?bamboo,cutting,board',
    slug: 'bamboo-cutting-board',
    rating: 4.5,
    reviewCount: 88,
    badge: null,
    category: 'home-garden',
    inStock: true,
  },
  {
    id: 'h-8',
    name: 'Vacuum Cleaner (Bagless)',
    price: 99.99,
    comparePrice: 129.99,
    image: 'https://source.unsplash.com/featured/800x600?vacuum,cleaner',
    slug: 'vacuum-cleaner-bagless',
    rating: 4.1,
    reviewCount: 65,
    badge: null,
    category: 'home-garden',
    inStock: false,
  },
  {
    id: 'h-9',
    name: 'Ceramic Dinnerware Set (16pc)',
    price: 79.99,
    comparePrice: 99.99,
    image: 'https://source.unsplash.com/featured/800x600?dinnerware,ceramic',
    slug: 'ceramic-dinnerware-set-16pc',
    rating: 4.2,
    reviewCount: 58,
    badge: null,
    category: 'home-garden',
    inStock: true,
  },
  {
    id: 'h-10',
    name: 'Air Purifier with HEPA Filter',
    price: 129.99,
    comparePrice: 149.99,
    image: 'https://source.unsplash.com/featured/800x600?air,purifier,hepa',
    slug: 'air-purifier-hepa',
    rating: 4.6,
    reviewCount: 120,
    badge: 'Limited',
    category: 'home-garden',
    inStock: true,
  },
  {
    id: 'h-11',
    name: 'Essential Oil Diffuser',
    price: 24.99,
    comparePrice: 29.99,
    image: 'https://source.unsplash.com/featured/800x600?oil,diffuser,aroma',
    slug: 'essential-oil-diffuser',
    rating: 4.4,
    reviewCount: 102,
    badge: null,
    category: 'home-garden',
    inStock: true,
  },
  {
    id: 'h-12',
    name: 'All-Season Duvet Comforter',
    price: 59.99,
    comparePrice: 79.99,
    image: 'https://source.unsplash.com/featured/800x600?duvet,comforter',
    slug: 'all-season-duvet-comforter',
    rating: 4.5,
    reviewCount: 90,
    badge: null,
    category: 'home-garden',
    inStock: true,
  },

  // Sports (12+)
  {
    id: 's-1',
    name: 'Yoga Mat (Non-Slip)',
    price: 24.99,
    comparePrice: 29.99,
    image: 'https://source.unsplash.com/featured/800x600?yoga,mat',
    slug: 'yoga-mat-non-slip',
    rating: 4.6,
    reviewCount: 140,
    badge: 'Best Seller',
    category: 'sports',
    inStock: true,
  },
  {
    id: 's-2',
    name: 'Adjustable Dumbbells (Pair)',
    price: 79.99,
    comparePrice: 99.99,
    image: 'https://source.unsplash.com/featured/800x600?dumbbells,weights',
    slug: 'adjustable-dumbbells-pair',
    rating: 4.4,
    reviewCount: 100,
    badge: null,
    category: 'sports',
    inStock: true,
  },
  {
    id: 's-3',
    name: 'Running Shoes',
    price: 69.99,
    comparePrice: 89.99,
    image: 'https://source.unsplash.com/featured/800x600?running,shoes',
    slug: 'running-shoes',
    rating: 4.5,
    reviewCount: 160,
    badge: 'Hot Deal',
    category: 'sports',
    inStock: true,
  },
  {
    id: 's-4',
    name: 'Fitness Resistance Bands',
    price: 19.99,
    comparePrice: 24.99,
    image: 'https://source.unsplash.com/featured/800x600?resistance,bands',
    slug: 'fitness-resistance-bands',
    rating: 4.3,
    reviewCount: 85,
    badge: null,
    category: 'sports',
    inStock: true,
  },
  {
    id: 's-5',
    name: 'Mountain Bike Helmet',
    price: 49.99,
    comparePrice: 59.99,
    image: 'https://source.unsplash.com/featured/800x600?bike,helmet',
    slug: 'mountain-bike-helmet',
    rating: 4.2,
    reviewCount: 70,
    badge: null,
    category: 'sports',
    inStock: true,
  },
  {
    id: 's-6',
    name: 'Stainless Steel Water Bottle',
    price: 14.99,
    comparePrice: 19.99,
    image:
      'https://source.unsplash.com/featured/800x600?stainless,water,bottle',
    slug: 'stainless-steel-water-bottle',
    rating: 4.7,
    reviewCount: 200,
    badge: 'New',
    category: 'sports',
    inStock: true,
  },
  {
    id: 's-7',
    name: 'Tennis Racket',
    price: 59.99,
    comparePrice: 79.99,
    image: 'https://source.unsplash.com/featured/800x600?tennis,racket',
    slug: 'tennis-racket',
    rating: 4.1,
    reviewCount: 66,
    badge: null,
    category: 'sports',
    inStock: true,
  },
  {
    id: 's-8',
    name: 'Football (Match Quality)',
    price: 29.99,
    comparePrice: 34.99,
    image: 'https://source.unsplash.com/featured/800x600?football,soccer,ball',
    slug: 'football-match-quality',
    rating: 4.3,
    reviewCount: 90,
    badge: null,
    category: 'sports',
    inStock: true,
  },
  {
    id: 's-9',
    name: 'Cycling Gloves',
    price: 17.99,
    comparePrice: 22.99,
    image: 'https://source.unsplash.com/featured/800x600?cycling,gloves',
    slug: 'cycling-gloves',
    rating: 4.2,
    reviewCount: 58,
    badge: null,
    category: 'sports',
    inStock: true,
  },
  {
    id: 's-10',
    name: 'Jump Rope',
    price: 12.99,
    comparePrice: 14.99,
    image: 'https://source.unsplash.com/featured/800x600?jump,rope',
    slug: 'jump-rope',
    rating: 4.0,
    reviewCount: 44,
    badge: null,
    category: 'sports',
    inStock: true,
  },
  {
    id: 's-11',
    name: 'Basketball',
    price: 24.99,
    comparePrice: 29.99,
    image: 'https://source.unsplash.com/featured/800x600?basketball,ball',
    slug: 'basketball',
    rating: 4.4,
    reviewCount: 76,
    badge: null,
    category: 'sports',
    inStock: false,
  },
  {
    id: 's-12',
    name: 'Home Gym Pull-Up Bar',
    price: 34.99,
    comparePrice: 39.99,
    image: 'https://source.unsplash.com/featured/800x600?pull-up,bar,gym',
    slug: 'home-gym-pull-up-bar',
    rating: 4.3,
    reviewCount: 82,
    badge: null,
    category: 'sports',
    inStock: true,
  },

  // Books (12+)
  {
    id: 'b-1',
    name: 'The Art of Coding',
    price: 24.99,
    comparePrice: 29.99,
    image:
      'https://source.unsplash.com/featured/800x600?coding,programming,book',
    slug: 'the-art-of-coding',
    rating: 4.7,
    reviewCount: 210,
    badge: 'Best Seller',
    category: 'books',
    inStock: true,
  },
  {
    id: 'b-2',
    name: 'Mystery in the Mountains',
    price: 14.99,
    comparePrice: 19.99,
    image: 'https://source.unsplash.com/featured/800x600?mystery,novel,book',
    slug: 'mystery-in-the-mountains',
    rating: 4.2,
    reviewCount: 88,
    badge: null,
    category: 'books',
    inStock: true,
  },
  {
    id: 'b-3',
    name: 'Cooking for Beginners',
    price: 19.99,
    comparePrice: 24.99,
    image: 'https://source.unsplash.com/featured/800x600?cooking,book',
    slug: 'cooking-for-beginners',
    rating: 4.4,
    reviewCount: 120,
    badge: null,
    category: 'books',
    inStock: true,
  },
  {
    id: 'b-4',
    name: 'Gardening Made Easy',
    price: 16.99,
    comparePrice: 21.99,
    image: 'https://source.unsplash.com/featured/800x600?gardening,book',
    slug: 'gardening-made-easy',
    rating: 4.3,
    reviewCount: 75,
    badge: null,
    category: 'books',
    inStock: true,
  },
  {
    id: 'b-5',
    name: 'History of Ancient Worlds',
    price: 22.99,
    comparePrice: 27.99,
    image: 'https://source.unsplash.com/featured/800x600?ancient,history,book',
    slug: 'history-of-ancient-worlds',
    rating: 4.1,
    reviewCount: 64,
    badge: null,
    category: 'books',
    inStock: true,
  },
  {
    id: 'b-6',
    name: 'Science Facts and Wonders',
    price: 21.99,
    comparePrice: 26.99,
    image: 'https://source.unsplash.com/featured/800x600?science,book',
    slug: 'science-facts-and-wonders',
    rating: 4.5,
    reviewCount: 98,
    badge: 'New',
    category: 'books',
    inStock: true,
  },
  {
    id: 'b-7',
    name: 'Fantasy Realms: Book One',
    price: 17.99,
    comparePrice: 22.99,
    image: 'https://source.unsplash.com/featured/800x600?fantasy,novel,book',
    slug: 'fantasy-realms-book-one',
    rating: 4.0,
    reviewCount: 55,
    badge: null,
    category: 'books',
    inStock: true,
  },
  {
    id: 'b-8',
    name: 'Business Strategy Essentials',
    price: 26.99,
    comparePrice: 31.99,
    image: 'https://source.unsplash.com/featured/800x600?business,book',
    slug: 'business-strategy-essentials',
    rating: 4.3,
    reviewCount: 85,
    badge: null,
    category: 'books',
    inStock: true,
  },
  {
    id: 'b-9',
    name: 'Photography Basics',
    price: 18.99,
    comparePrice: 23.99,
    image: 'https://source.unsplash.com/featured/800x600?photography,book',
    slug: 'photography-basics',
    rating: 4.2,
    reviewCount: 70,
    badge: null,
    category: 'books',
    inStock: true,
  },
  {
    id: 'b-10',
    name: 'Health & Wellness Guide',
    price: 20.99,
    comparePrice: 25.99,
    image: 'https://source.unsplash.com/featured/800x600?health,wellness,book',
    slug: 'health-and-wellness-guide',
    rating: 4.4,
    reviewCount: 92,
    badge: null,
    category: 'books',
    inStock: true,
  },
  {
    id: 'b-11',
    name: 'Travel the World on a Budget',
    price: 23.99,
    comparePrice: 28.99,
    image: 'https://source.unsplash.com/featured/800x600?travel,book',
    slug: 'travel-the-world-on-a-budget',
    rating: 4.1,
    reviewCount: 66,
    badge: null,
    category: 'books',
    inStock: true,
  },
  {
    id: 'b-12',
    name: 'Mindfulness and Meditation',
    price: 19.99,
    comparePrice: 24.99,
    image:
      'https://source.unsplash.com/featured/800x600?mindfulness,meditation,book',
    slug: 'mindfulness-and-meditation',
    rating: 4.5,
    reviewCount: 140,
    badge: 'Limited',
    category: 'books',
    inStock: true,
  },
];

export const CATEGORY_ORDER: CategoryKey[] = [
  'electronics',
  'clothing',
  'home-garden',
  'sports',
  'books',
];

export function getProductBySlug(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: CategoryKey) {
  return PRODUCTS.filter((p) => p.category === category);
}
